import 'dart:math';

/// A list of quotes.
const List<String> quotes = <String>[
  "Tough times don't last, only tough people last",
  "Behind every successful man, there's a story to tell",
  'Only the tallest tree has the experience of the roughest wind',
  'Don’t tell anyone what you’re doing until it’s done',
  "The very beautiful mirror can be very sharp when it's broken",
  'Stand like a tree and if you’re falling down, fall like a seed',
  'The true test of leadership is how you function',
  'Those who truly love will never leave you',
  'The most dangerous people are the ones who are closest to you',
  'All birds stop flying when it rains but the eagle flies higher, and hence continues to fly',
  'All problems that you are facing are common, attitude makes the difference',
  'Only you can destroy yourself',
  "Hope doesn't kill you, It just makes you live for another day",
  'Years later a collection of mistakes is what is called experience',
  'Apologizing does not always mean you are wrong and the other person is right It just means you value your relationship more than your ego',
  'Never judge a person by their choices',
  'There is a hidden blessing in every struggle',
  'Worry never robs tomorrow of its sorrow, it only saps today of its joy',
  'One of the happiest moments in life is to let go of what you can’t change',
  'Trees lose everything in winter and they still stand and wait for better days',
  'Better days are coming',
  'Never be a prisoner of your past, it was just a lesson, not a life sentence',
  "The sun doesn't ask for praise, and yet it rises every morning",
  'Two things define you, your patience when you have nothing, and your attitude when you have everything',
  'Patience is not the ability to wait, but the ability to keep a good attitude while waiting',
  'No matter how long you have traveled in the wrong direction, you can always turn around',
  'Punctuality is not about being on time, but about respecting your own commitments',
  'if you focus on the pain you will continue to suffer, but if you focus on the lesson, you will continue to grow',
  'Sometimes life doesn’t give you what you want, not because you don’t deserve it, but because you deserve more',
  'Let the situations change us',
  'A negative mind finds faults in every situation But a positive mind finds opportunities in every situation',
  'Mistakes increase your experience and experience decreases your mistakes',
  'Friendship is about who walked into your life, said "I’m here for you", and proved it',
  'Self-disciplined begins with the mastery of your thoughts',
  "Don't be distracted by criticism Remember, the only taste of success some people have is when they take a bite out of you",
  "Family is not about blood It's about who is willing to hold your hand when you need it the most",
  'when the roots are deep, there is no reason to fear the wind',
  'The greatest prison people live in is the fear of what others think',
  "Ships don't sink because of the water around them, but because of the water that gets in them",
  'It takes nothing to join the crowd but it takes everything to stand alone',
  'What you allow is what will continue',
  "If you don't like where you are then move, you are not a tree",
  'Positive thinking is about accepting that whatever will happen will be the best',
  'Never be afraid of scars',
  'Maturity is not measured by age, its an attitude built by experience',
  'When the wrong people leave your life, the right things start to happen',
  'Not everyone will understand your journey',
  'If you focus on the problem you will continue to have more problems',
  'Learn not to announce until it is not done',
  "An umbrella can't stop the rain yet it can still make us stand in the rain",
  'People only bring up your past when they are intimidated by your present',
  'A seed grows with no sound, but a tree falls with huge noise',
  'No lock is made without a key',
  'Happiness is not a destination, it is a journey',
  'You attract what you are, not what you want',
  'Sometimes peace is better than being right',
  'Some people are born with only goal to block others from shinning',
  'An arrow can only be shot by first pulling it backwards',
  "Don't blame a clown for acting like a clown",
  "Hunters can't afford to make noise",
];

/// Returns random quote.
String randQuote() {
  final Random rand = Random();
  return quotes[rand.nextInt(quotes.length - 1)];
}
