include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/resources/configs.dart

linter:
  rules:
    - camel_case_types
    - package_api_docs
    - public_member_api_docs
    - slash_for_doc_comments
    