name: habitflow
description: Build, Break, And Sustain Habits
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_iconpicker: ^2.0.0
  path_provider: ^1.6.11
  sembast: ^2.4.7+4
  bottom_navy_bar: ^5.4.0
  random_string: ^2.1.0
  provider: ^4.3.1
  flutter_neumorphic: ^3.0.1
  google_fonts: ^1.1.0
  sembast_web: ^1.2.0
  flutter_colorpicker: ^0.3.4
  weekday_selector: ^0.4.0
  percent_indicator: ^2.1.5
  
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 

dev_dependencies:
  easy_localization: ^2.3.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

  