name: habitflow
description: Build, Break, And Sustain Habits
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter_iconpicker: ^2.0.0
  firebase_admob: ^0.9.3+4
  path_provider: ^1.6.11
  bottom_navy_bar: ^5.4.0
  random_string: ^2.1.0
  provider: ^4.3.1
  flutter_neumorphic: ^3.0.1
  outline_material_icons: ^0.1.1
  confetti: ^0.5.4
  webview_flutter: ^0.3.22+1
  flutter_colorpicker: ^0.3.4
  firebase_analytics: ^5.0.16
  flutter_slidable: ^0.5.5
  weekday_selector: ^0.4.0
  percent_indicator: ^2.1.5
  tinycolor: ^1.0.2
  day_night_time_picker: ^0.2.0+1
  share: 0.6.4+3
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  audioplayers: ^0.15.1
  intro_slider: ^2.3.1
  firebase_core: ^0.4.5
  global_configuration: ^1.5.0
  easy_localization: ^2.3.2
  flutter_local_notifications: ^1.4.4+2
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter


dev_dependencies:
  lint: ^1.0.0
  import_sorter: ^4.2.1
  hive_generator: ^0.7.1
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/translations/
    - assets/sounds/
    - assets/images/
    - assets/cfg/
  uses-material-design: true

  