name: habitflow
description: Build, Break, And Sustain Habits
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_iconpicker: ^2.0.0
  path_provider: ^1.6.11
  sembast: ^2.4.7+4
  bottom_navy_bar: ^5.4.0
  random_string: ^2.1.0
  provider: ^4.3.1
  flutter_neumorphic: ^3.0.1
  google_fonts: ^1.1.0
  sembast_web: ^1.2.0
  flutter_colorpicker: ^0.3.4
  flutter_slidable: ^0.5.5
  weekday_selector: ^0.4.0
  after_layout: ^1.0.7+2
  device_preview: ^0.4.7
  percent_indicator: ^2.1.5
  theme_provider: ^0.4.0+1
  tinycolor: ^1.0.2
  day_night_time_picker: ^0.2.0+1
  audioplayers: ^0.15.1
  intro_slider: ^2.3.1
  easy_localization: ^2.3.2
  shared_preferences: ^0.5.8
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter


dev_dependencies:
  lint: ^1.0.0
  import_sorter: ^4.2.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/translations/en.json
    - assets/images/logo.png
    - assets/sounds/success.mpeg
    - assets/sounds/failure.mpeg
    - assets/sounds/skip.mpeg
    - packages/day_night_time_picker/assets/sun.png
    - packages/day_night_time_picker/assets/moon.png
  uses-material-design: true

  